version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - mkdir nestjs
      - mv package-dist.json nestjs/package.json
      - cp -R dist/ node_modules/ nestjs
artifacts:
  files: nestjs/**/*
  base-directory: nestjs